name: Update Catalog Details

# Controls when the workflow will run
on:
  # Allows you to run this workflow from another workflow
  workflow_call:
    inputs:
      referenceName:
        required: true
        type: string       
      runNumber:
        required: true
        type: string   
      referenceType:
        required: true
        type: string   
      repository:
        required: true
        type: string 
      owner:
        required: true
        type: string
    secrets:
      api-key:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update_catalog_details:
      name: Update Catalog Details
      runs-on: windows-latest
      permissions: write-all
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v4
        
        - name: readDir
          run: dir   

        - name: Initialize
          run: |
            echo "workspace" ${{ github.workspace }}
            echo "github url" ${{ github.repositoryUrl }}
            echo "ref name" ${{ inputs.referenceName }}
            echo "run number" ${{ inputs.runNumber }}
            echo "ref type" ${{ inputs.referenceType }}
            echo "repository" ${{ inputs.repository }}

        - name: Install .NET Tools
          run: |
            dotnet tool install -g Skyline.DataMiner.CICD.Tools.CatalogUpload
            dotnet tool install -g Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml --prerelease

        - name: Create or Extend Catalog.yml
          env:
            githubtoken: ${{ secrets.GITHUB_TOKEN }}
          run: |
            github-to-catalog-yaml --workspace "${{ github.workspace }}" --github-token ${{ env.githubtoken }} --github-repository "${{github.repository }}"
             
        - name: Check if catalog.yml or manifest.yml exists
          id: check_files
          run: |
            if [ -f "${{ github.workspace }}/catalog.yml" ]; then
              echo "catalogDetails=catalog.yml" >> $GITHUB_ENV
            elif [ -f "${{ github.workspace }}/manifest.yml" ]; then
              echo "catalogDetails=manifest.yml" >> $GITHUB_ENV
            else
              echo "No valid file found!"
              exit 1
    
        - uses: actions/upload-artifact@v4
          if: env.catalogDetails != ''
          with:
            name: Catalog Details
            path: "${{ github.workspace }}/${{ env.catalogDetails }}"