name: Update Catalog Details

# Controls when the workflow will run
on:
  # Allows you to run this workflow from another workflow
  workflow_call:
    inputs:
      referenceName:
        required: true
        type: string       
      runNumber:
        required: true
        type: string   
      referenceType:
        required: true
        type: string   
      repository:
        required: true
        type: string 
      owner:
        required: true
        type: string
    secrets:
      api-key:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update_catalog_details:
      name: Update Catalog Details
      runs-on: windows-latest
      permissions:
        contents: write
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v4
        
        - name: Initialize
          run: |
            echo "workspace" ${{ github.workspace }}
            echo "github url" ${{ github.repositoryUrl }}
            echo "ref name" ${{ inputs.referenceName }}
            echo "run number" ${{ inputs.runNumber }}
            echo "ref type" ${{ inputs.referenceType }}
            echo "repository" ${{ inputs.repository }}
                        
        - name: Install .NET Tools
          run: |
            dotnet tool install -g Skyline.DataMiner.CICD.Tools.CatalogUpload
            dotnet tool install -g Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml --prerelease
        
                      
        - name: TEST Delete Catalog.yml
          shell: pwsh
          run: |
            $filePath = "${{ github.workspace }}\catalog.yml"
            Add-Content -Path $filePath -Value ""
            Write-Host "Appended 'test' to catalog.yml"
  
        - name: Create or Extend Catalog.yml
          run: |
            github-to-catalog-yaml --workspace "${{ github.workspace }}" --github-token ${{ secrets.GITHUB_TOKEN }} --github-repository "${{ github.repository }}" --catalog-identifier "${{ vars.catalogIdentifier }}"
       
        - name: Check if catalog.yml or manifest.yml exists
          id: check_files
          shell: pwsh
          run: |
            if (Test-Path "${{ github.workspace }}/catalog.yml") {
              echo "catalogDetails=catalog.yml" >> $env:GITHUB_ENV
            }
            elseif (Test-Path "${{ github.workspace }}/manifest.yml") {
              echo "catalogDetails=manifest.yml" >> $env:GITHUB_ENV
            }
            else {
              Write-Host "No valid file found!"
              exit 1
            }
        
        - uses: actions/upload-artifact@v4
          if: env.catalogDetails != ''
          with:
            name: Catalog Details
            path: "${{ github.workspace }}/${{ env.catalogDetails }}"

        - name: Commit changes
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add "${{ github.workspace }}\.GitHubToCatalogYaml\auto-generated-catalog.yml"
            
            # Check if there are any changes to be committed
            git diff --staged --quiet
            if ($LASTEXITCODE -ne 0) {
              git commit -m "auto-generated"
            }
            else {
              Write-Host "No changes to commit."
            }
          
        - name: Push changes
          run: |
            git push
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}